=== fbelluomini2/Codifica_di_Testi/Esercizi/Esercizio Testo/testo.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT ns1:TEI (ns1:teiHeader,ns1:text)>
<!ATTLIST ns1:TEI
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:teiHeader (ns1:fileDesc)>
<!ATTLIST ns1:teiHeader
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  xml:lang NMTOKEN #REQUIRED>

<!ELEMENT ns1:text (ns1:body)>
<!ATTLIST ns1:text
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  xml:id NMTOKEN #REQUIRED
  xml:lang NMTOKEN #REQUIRED>

<!ELEMENT ns1:fileDesc (ns1:titleStmt,ns1:publicationStmt,
                        ns1:sourceDesc)>
<!ATTLIST ns1:fileDesc
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:body (ns1:div)>
<!ATTLIST ns1:body
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  xml:id CDATA #REQUIRED>

<!ELEMENT ns1:titleStmt (ns1:title,ns1:author)>
<!ATTLIST ns1:titleStmt
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:publicationStmt (ns1:publisher)>
<!ATTLIST ns1:publicationStmt
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:sourceDesc (ns1:msDesc)>
<!ATTLIST ns1:sourceDesc
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:div (ns1:p)+>
<!ATTLIST ns1:div
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  n NMTOKEN #REQUIRED>

<!ELEMENT ns1:title (ns1:htmlCode)>
<!ATTLIST ns1:title
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  type NMTOKEN #REQUIRED>

<!ELEMENT ns1:author EMPTY>
<!ATTLIST ns1:author
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  ref CDATA #REQUIRED>

<!ELEMENT ns1:publisher EMPTY>
<!ATTLIST ns1:publisher
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  ref CDATA #REQUIRED
  xml:lang NMTOKEN #REQUIRED>

<!ELEMENT ns1:msDesc (ns1:msIdentifier)>
<!ATTLIST ns1:msDesc
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:p EMPTY>
<!ATTLIST ns1:p
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  n CDATA #REQUIRED>

<!ELEMENT ns1:htmlCode (#PCDATA)>
<!ATTLIST ns1:htmlCode
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:msIdentifier (ns1:repository)>
<!ATTLIST ns1:msIdentifier
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:repository EMPTY>
<!ATTLIST ns1:repository
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  ref CDATA #REQUIRED
  role NMTOKEN #REQUIRED>

=== fbelluomini2/Codifica_di_Testi/Esercizi/Esercizio Testo/Esercizio_Testo.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE TEI SYSTEM "testo.dtd" >

<!-- This document contains data on Codifica di Testi.

    Filename: Esercizio_Testo.xml 
    Author: Francesca Belluomini
    Date: 20 agosto 2021
-->

<TEI xmlns="http://www.tei-c.org/ns/1.0">
 
    <teiHeader xml:lang="eng">
   <fileDesc>
   
     <titleStmt>
	   <title type="main"><htmlCode> <![CDATA[ <h1>I Promessi Sposi</h1>]]> </htmlCode></title>
	   <author ref="#AM">di Alessandro Manzoni</author>
	 </titleStmt>
	 
	 <publicationStmt>
	    <publisher xml:lang="it" ref="https://www.liberliber.it/online/"> Liberliber</publisher>
	 </publicationStmt>
	 
	 <sourceDesc>
        <msDesc>
          <msIdentifier>
		     <repository role="library" ref="https://www.liberliber.it/online/opere/libri/opere-p/">Liberliber </repository>
		  </msIdentifier>
        </msDesc>	
	 </sourceDesc>
  </fileDesc>

</teiHeader>

<text xml:lang="eng" xml:id="Libro">
  <body xml:id="Promessi Sposi">
   <div n="ch1">

      <p n="1">
	     Quel ramo del lago di Como, che volge a mezzogiorno, tra due catene non interrotte di monti, tutto a seni e a golfi, 
		 a seconda dello sporgere e del rientrare di quelli, vien, quasi a un tratto, a ristringersi, e a prender corso e figura di fiume, 
		 tra un promontorio a destra, e un'ampia costiera dall'altra parte; e il ponte, che ivi congiunge le due rive, 
		 par che renda ancor più sensibile all'occhio questa trasformazione, e segni il punto in cui il lago cessa, e l'Adda rincomincia, 
		 per ripigliar poi nome di lago dove le rive, allontanandosi di nuovo, lascian l'acqua distendersi e 
		 rallentarsi in nuovi golfi e in nuovi seni. 
	 </p>

     <p n="2">
	   La costiera, formata da deposito di tre grossi torrenti, scende appoggiata a due monti contigui, l'uno detto di san Martino, l'altro, 
	   con voce lombarda, il Resegone, dai molti suoi cocuzzoli in fila, che in vero lo fanno somigliare a una sega: talchè
       non è chi, al primo vederlo, purchè sia di fronte, come per esempio di su le mura di Milano che guardano a settentrione, 
	   non lo discerna tosto, a un tal contrassegno, in quella lunga e vasta giogaia, dagli altri monti di nome più oscuro e di forma più comune.
	 </p> 

     <p n="3">
	   Per un buon pezzo, la costa sale con un pendìo lento e continuo; poi si rompe in poggi e in valloncelli, in erte e in ispianate, 
	   secondo l'ossatura de' due monti, e il lavoro dell'acque.
	 </p>

     <p n="4">
	   Il lembo estremo, tagliato dalle foci de' torrenti, è quasi tutto ghiaia e ciottoloni; il resto, campi e vigne, sparse di terre, di ville, 
	   di casali; in qualche parte boschi, che si prolungano su per la montagna.
	 </p>

      <p n="5">
	    Lecco, la principale di quelle terre, e che dà nome al territorio, giace poco discosto dal ponte, alla riva del lago, anzi viene in parte a
        trovarsi nel lago stesso, quando questo ingrossa: un gran borgo al giorno d'oggi, e che s'incammina a diventar città. 
	  </p>

       <p n="6">
	    Ai tempi in cui accaddero i fatti che prendiamo a raccontare, quel borgo, già considerabile, era anche un castello, e aveva perciò 
		l'onore d'alloggiare un comandante, e il vantaggio di possedere una stabile guarnigione di soldati spagnoli, 
		che insegnavan la modestia alle fanciulle e alle donne del paese, accarezzavan di tempo in tempo le spalle a qualche marito, 
		a qualche padre; e, sul finir dell'estate, non mancavan mai di spandersi nelle vigne, per diradar l'uve, e alleggerire a' 
		contadini le fatiche della vendemmia. 
	  </p>

      <p n="7">
	   Dall'una all'altra di quelle terre, dall'alture alla riva, da un poggio all'altro, correvano, e corrono tuttavia, strade e stradette, 
	   più o men ripide, o piane; ogni tanto affondate, sepolte tra due muri, donde, alzando lo sguardo, non iscoprite che un pezzo di cielo e
       qualche vetta di monte; ogni tanto elevate su terrapieni aperti: e da qui la vista spazia per prospetti più o meno
       estesi, ma ricchi sempre e sempre qualcosa nuovi, secondo che i diversi punti piglian più o meno della vasta scena circostante, e secondo 
       che questa o quella parte campeggia o si scorcia, spunta o sparisce a vicenda.
	  </p>

      <p n="8">
	   Dove un pezzo, dove un altro, dove una lunga distesa di quel vasto e variato specchio dell'acqua; di qua lago, chiuso all'estremità 
	   o piuttosto smarrito in un gruppo, in un andirivieni di montagne, e di mano in mano più allargato tra altri monti che si spiegano, 
	   a uno a uno, allo sguardo, e che l'acqua riflette capovolti, co' paesetti posti sulle rive; di là braccio di fiume, poi lago, poi fiume ancora, 
	   che va a perdersi in lucido serpeggiamento pur tra' monti che l'accompagnano, degradando via via, e perdendosi quasi anch'essi nell'orizzonte.
	  </p>

	</div>  
  </body>
</text>

</TEI>
